---
title: "ICPC-2 codes / ICPC-2-koder"
date: "2023-03-24"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ICPC-2 codes / ICPC-2-koder}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---



<!--html_preserve--><div id="yugbqoazwu" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#yugbqoazwu .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#yugbqoazwu .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yugbqoazwu .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#yugbqoazwu .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yugbqoazwu .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yugbqoazwu .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yugbqoazwu .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yugbqoazwu .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#yugbqoazwu .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#yugbqoazwu .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#yugbqoazwu .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#yugbqoazwu .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#yugbqoazwu .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#yugbqoazwu .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#yugbqoazwu .gt_from_md > :first-child {
  margin-top: 0;
}

#yugbqoazwu .gt_from_md > :last-child {
  margin-bottom: 0;
}

#yugbqoazwu .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#yugbqoazwu .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#yugbqoazwu .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#yugbqoazwu .gt_row_group_first td {
  border-top-width: 2px;
}

#yugbqoazwu .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yugbqoazwu .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#yugbqoazwu .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#yugbqoazwu .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yugbqoazwu .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yugbqoazwu .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#yugbqoazwu .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#yugbqoazwu .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yugbqoazwu .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yugbqoazwu .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yugbqoazwu .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yugbqoazwu .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yugbqoazwu .gt_left {
  text-align: left;
}

#yugbqoazwu .gt_center {
  text-align: center;
}

#yugbqoazwu .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yugbqoazwu .gt_font_normal {
  font-weight: normal;
}

#yugbqoazwu .gt_font_bold {
  font-weight: bold;
}

#yugbqoazwu .gt_font_italic {
  font-style: italic;
}

#yugbqoazwu .gt_super {
  font-size: 65%;
}

#yugbqoazwu .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#yugbqoazwu .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#yugbqoazwu .gt_indent_1 {
  text-indent: 5px;
}

#yugbqoazwu .gt_indent_2 {
  text-indent: 10px;
}

#yugbqoazwu .gt_indent_3 {
  text-indent: 15px;
}

#yugbqoazwu .gt_indent_4 {
  text-indent: 20px;
}

#yugbqoazwu .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="4" class="gt_heading gt_title gt_font_normal" style>ICPC-2-koder i NorSySS</td>
    </tr>
    <tr>
      <td colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Norsk bokmål</td>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="ICPC-2-koder">ICPC-2-koder</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Beskrivelser">Beskrivelser</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Komponent">Komponent</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Allment og uspesifisert">Allment og uspesifisert</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub">a02</th>
<td headers="Allment og uspesifisert stub_1_1 icpc2raw_code" class="gt_row gt_center">A02</td>
<td headers="Allment og uspesifisert stub_1_1 icpc2group_description_nb" class="gt_row gt_left">Frysninger</td>
<td headers="Allment og uspesifisert stub_1_1 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub">a03</th>
<td headers="Allment og uspesifisert stub_1_2 icpc2raw_code" class="gt_row gt_center">A03</td>
<td headers="Allment og uspesifisert stub_1_2 icpc2group_description_nb" class="gt_row gt_left">Feber</td>
<td headers="Allment og uspesifisert stub_1_2 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub">a05</th>
<td headers="Allment og uspesifisert stub_1_3 icpc2raw_code" class="gt_row gt_center">A05</td>
<td headers="Allment og uspesifisert stub_1_3 icpc2group_description_nb" class="gt_row gt_left">Sykdomsfølelse</td>
<td headers="Allment og uspesifisert stub_1_3 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_left gt_stub">a71</th>
<td headers="Allment og uspesifisert stub_1_4 icpc2raw_code" class="gt_row gt_center">A71</td>
<td headers="Allment og uspesifisert stub_1_4 icpc2group_description_nb" class="gt_row gt_left">Meslinger</td>
<td headers="Allment og uspesifisert stub_1_4 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_left gt_stub">a72</th>
<td headers="Allment og uspesifisert stub_1_5 icpc2raw_code" class="gt_row gt_center">A72</td>
<td headers="Allment og uspesifisert stub_1_5 icpc2group_description_nb" class="gt_row gt_left">Vannkopper</td>
<td headers="Allment og uspesifisert stub_1_5 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_left gt_stub">a73</th>
<td headers="Allment og uspesifisert stub_1_6 icpc2raw_code" class="gt_row gt_center">A73</td>
<td headers="Allment og uspesifisert stub_1_6 icpc2group_description_nb" class="gt_row gt_left">Malaria</td>
<td headers="Allment og uspesifisert stub_1_6 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_left gt_stub">a74</th>
<td headers="Allment og uspesifisert stub_1_7 icpc2raw_code" class="gt_row gt_center">A74</td>
<td headers="Allment og uspesifisert stub_1_7 icpc2group_description_nb" class="gt_row gt_left">Røde hunder</td>
<td headers="Allment og uspesifisert stub_1_7 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_8" scope="row" class="gt_row gt_left gt_stub">a75</th>
<td headers="Allment og uspesifisert stub_1_8 icpc2raw_code" class="gt_row gt_center">A75</td>
<td headers="Allment og uspesifisert stub_1_8 icpc2group_description_nb" class="gt_row gt_left">Mononukleose</td>
<td headers="Allment og uspesifisert stub_1_8 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_9" scope="row" class="gt_row gt_left gt_stub">a76</th>
<td headers="Allment og uspesifisert stub_1_9 icpc2raw_code" class="gt_row gt_center">A76</td>
<td headers="Allment og uspesifisert stub_1_9 icpc2group_description_nb" class="gt_row gt_left">Virussykdom med utslett IKA</td>
<td headers="Allment og uspesifisert stub_1_9 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_10" scope="row" class="gt_row gt_left gt_stub">a77</th>
<td headers="Allment og uspesifisert stub_1_10 icpc2raw_code" class="gt_row gt_center">A77</td>
<td headers="Allment og uspesifisert stub_1_10 icpc2group_description_nb" class="gt_row gt_left">Virussykdom IKA</td>
<td headers="Allment og uspesifisert stub_1_10 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_11" scope="row" class="gt_row gt_left gt_stub">a78</th>
<td headers="Allment og uspesifisert stub_1_11 icpc2raw_code" class="gt_row gt_center">A78</td>
<td headers="Allment og uspesifisert stub_1_11 icpc2group_description_nb" class="gt_row gt_left">Infeksjonssykdom IKA</td>
<td headers="Allment og uspesifisert stub_1_11 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Blod, bloddannende organer og immunsystemet">Blod, bloddannende organer og immunsystemet</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_12" scope="row" class="gt_row gt_left gt_stub">b02</th>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_12 icpc2raw_code" class="gt_row gt_center">B02</td>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_12 icpc2group_description_nb" class="gt_row gt_left">Lymfeknuter forstørrede/smertefulle</td>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_12 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_13" scope="row" class="gt_row gt_left gt_stub">b70</th>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_13 icpc2raw_code" class="gt_row gt_center">B70</td>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_13 icpc2group_description_nb" class="gt_row gt_left">Lymfadenitt akutt</td>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_13 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_14" scope="row" class="gt_row gt_left gt_stub">b71</th>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_14 icpc2raw_code" class="gt_row gt_center">B71</td>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_14 icpc2group_description_nb" class="gt_row gt_left">Lymfadenitt kronisk/uspesifikk</td>
<td headers="Blod, bloddannende organer og immunsystemet stub_1_14 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Fordøyelsessystemet">Fordøyelsessystemet</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_15" scope="row" class="gt_row gt_left gt_stub">d01</th>
<td headers="Fordøyelsessystemet stub_1_15 icpc2raw_code" class="gt_row gt_center">D01</td>
<td headers="Fordøyelsessystemet stub_1_15 icpc2group_description_nb" class="gt_row gt_left">Abdominalsmerte/krampe generell</td>
<td headers="Fordøyelsessystemet stub_1_15 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_16" scope="row" class="gt_row gt_left gt_stub">d02</th>
<td headers="Fordøyelsessystemet stub_1_16 icpc2raw_code" class="gt_row gt_center">D02</td>
<td headers="Fordøyelsessystemet stub_1_16 icpc2group_description_nb" class="gt_row gt_left">Abdominalsmerte epigastriet</td>
<td headers="Fordøyelsessystemet stub_1_16 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_17" scope="row" class="gt_row gt_left gt_stub">d06</th>
<td headers="Fordøyelsessystemet stub_1_17 icpc2raw_code" class="gt_row gt_center">D06</td>
<td headers="Fordøyelsessystemet stub_1_17 icpc2group_description_nb" class="gt_row gt_left">Abdonimalsmerte lokalisert IKA</td>
<td headers="Fordøyelsessystemet stub_1_17 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_18" scope="row" class="gt_row gt_left gt_stub">d08</th>
<td headers="Fordøyelsessystemet stub_1_18 icpc2raw_code" class="gt_row gt_center">D08</td>
<td headers="Fordøyelsessystemet stub_1_18 icpc2group_description_nb" class="gt_row gt_left">Flatulens/oppblåsthet/raping</td>
<td headers="Fordøyelsessystemet stub_1_18 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_19" scope="row" class="gt_row gt_left gt_stub">d09</th>
<td headers="Fordøyelsessystemet stub_1_19 icpc2raw_code" class="gt_row gt_center">D09</td>
<td headers="Fordøyelsessystemet stub_1_19 icpc2group_description_nb" class="gt_row gt_left">Kvalme</td>
<td headers="Fordøyelsessystemet stub_1_19 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_20" scope="row" class="gt_row gt_left gt_stub">d10</th>
<td headers="Fordøyelsessystemet stub_1_20 icpc2raw_code" class="gt_row gt_center">D10</td>
<td headers="Fordøyelsessystemet stub_1_20 icpc2group_description_nb" class="gt_row gt_left">Oppkast/brekninger</td>
<td headers="Fordøyelsessystemet stub_1_20 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_21" scope="row" class="gt_row gt_left gt_stub">d11</th>
<td headers="Fordøyelsessystemet stub_1_21 icpc2raw_code" class="gt_row gt_center">D11</td>
<td headers="Fordøyelsessystemet stub_1_21 icpc2group_description_nb" class="gt_row gt_left">Diaré</td>
<td headers="Fordøyelsessystemet stub_1_21 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_22" scope="row" class="gt_row gt_left gt_stub">d14</th>
<td headers="Fordøyelsessystemet stub_1_22 icpc2raw_code" class="gt_row gt_center">D14</td>
<td headers="Fordøyelsessystemet stub_1_22 icpc2group_description_nb" class="gt_row gt_left">Oppkast med blod/hematemese</td>
<td headers="Fordøyelsessystemet stub_1_22 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_23" scope="row" class="gt_row gt_left gt_stub">d18</th>
<td headers="Fordøyelsessystemet stub_1_23 icpc2raw_code" class="gt_row gt_center">D18</td>
<td headers="Fordøyelsessystemet stub_1_23 icpc2group_description_nb" class="gt_row gt_left">Endring i avføring/avføringsvane</td>
<td headers="Fordøyelsessystemet stub_1_23 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_24" scope="row" class="gt_row gt_left gt_stub">d25</th>
<td headers="Fordøyelsessystemet stub_1_24 icpc2raw_code" class="gt_row gt_center">D25</td>
<td headers="Fordøyelsessystemet stub_1_24 icpc2group_description_nb" class="gt_row gt_left">Utspilt abdomen</td>
<td headers="Fordøyelsessystemet stub_1_24 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_25" scope="row" class="gt_row gt_left gt_stub">d29</th>
<td headers="Fordøyelsessystemet stub_1_25 icpc2raw_code" class="gt_row gt_center">D29</td>
<td headers="Fordøyelsessystemet stub_1_25 icpc2group_description_nb" class="gt_row gt_left">Fordøyelsesyst symptomer/plager IKA</td>
<td headers="Fordøyelsessystemet stub_1_25 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_26" scope="row" class="gt_row gt_left gt_stub">d70</th>
<td headers="Fordøyelsessystemet stub_1_26 icpc2raw_code" class="gt_row gt_center">D70</td>
<td headers="Fordøyelsessystemet stub_1_26 icpc2group_description_nb" class="gt_row gt_left">Tarminfeksjon</td>
<td headers="Fordøyelsessystemet stub_1_26 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_27" scope="row" class="gt_row gt_left gt_stub">d73</th>
<td headers="Fordøyelsessystemet stub_1_27 icpc2raw_code" class="gt_row gt_center">D73</td>
<td headers="Fordøyelsessystemet stub_1_27 icpc2group_description_nb" class="gt_row gt_left">Gastroenteritt antatt infeksiøs</td>
<td headers="Fordøyelsessystemet stub_1_27 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_28" scope="row" class="gt_row gt_left gt_stub">d87</th>
<td headers="Fordøyelsessystemet stub_1_28 icpc2raw_code" class="gt_row gt_center">D87</td>
<td headers="Fordøyelsessystemet stub_1_28 icpc2group_description_nb" class="gt_row gt_left">Funksjonelle plager magesekk</td>
<td headers="Fordøyelsessystemet stub_1_28 component_nb" class="gt_row gt_left">Annet</td></tr>
    <tr><th id="stub_1_29" scope="row" class="gt_row gt_left gt_stub">d99</th>
<td headers="Fordøyelsessystemet stub_1_29 icpc2raw_code" class="gt_row gt_center">D99</td>
<td headers="Fordøyelsessystemet stub_1_29 icpc2group_description_nb" class="gt_row gt_left">Sykdom i fordøyelsessystemet IKA</td>
<td headers="Fordøyelsessystemet stub_1_29 component_nb" class="gt_row gt_left">Annet</td></tr>
    <tr><th id="stub_1_30" scope="row" class="gt_row gt_left gt_stub">gastroenteritis</th>
<td headers="Fordøyelsessystemet stub_1_30 icpc2raw_code" class="gt_row gt_center">D11, D70, D73</td>
<td headers="Fordøyelsessystemet stub_1_30 icpc2group_description_nb" class="gt_row gt_left">Mage-tarminfeksjoner</td>
<td headers="Fordøyelsessystemet stub_1_30 component_nb" class="gt_row gt_left">Kombinasjon</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Øye">Øye</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_31" scope="row" class="gt_row gt_left gt_stub">f70</th>
<td headers="Øye stub_1_31 icpc2raw_code" class="gt_row gt_center">F70</td>
<td headers="Øye stub_1_31 icpc2group_description_nb" class="gt_row gt_left">Infeksiøs konjunktivitt</td>
<td headers="Øye stub_1_31 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_32" scope="row" class="gt_row gt_left gt_stub">f73</th>
<td headers="Øye stub_1_32 icpc2raw_code" class="gt_row gt_center">F73</td>
<td headers="Øye stub_1_32 icpc2group_description_nb" class="gt_row gt_left">Øye infeksjon/betennelse IKA</td>
<td headers="Øye stub_1_32 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Øre">Øre</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_33" scope="row" class="gt_row gt_left gt_stub">h01</th>
<td headers="Øre stub_1_33 icpc2raw_code" class="gt_row gt_center">H01</td>
<td headers="Øre stub_1_33 icpc2group_description_nb" class="gt_row gt_left">Øresmerte/øreverk</td>
<td headers="Øre stub_1_33 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_34" scope="row" class="gt_row gt_left gt_stub">h04</th>
<td headers="Øre stub_1_34 icpc2raw_code" class="gt_row gt_center">H04</td>
<td headers="Øre stub_1_34 icpc2group_description_nb" class="gt_row gt_left">Øreflod/sekresjon</td>
<td headers="Øre stub_1_34 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_35" scope="row" class="gt_row gt_left gt_stub">h13</th>
<td headers="Øre stub_1_35 icpc2raw_code" class="gt_row gt_center">H13</td>
<td headers="Øre stub_1_35 icpc2group_description_nb" class="gt_row gt_left">Øreplugg/øretetthet</td>
<td headers="Øre stub_1_35 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_36" scope="row" class="gt_row gt_left gt_stub">h29</th>
<td headers="Øre stub_1_36 icpc2raw_code" class="gt_row gt_center">H29</td>
<td headers="Øre stub_1_36 icpc2group_description_nb" class="gt_row gt_left">Øre symptomer/plager IKA</td>
<td headers="Øre stub_1_36 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_37" scope="row" class="gt_row gt_left gt_stub">h71</th>
<td headers="Øre stub_1_37 icpc2raw_code" class="gt_row gt_center">H71</td>
<td headers="Øre stub_1_37 icpc2group_description_nb" class="gt_row gt_left">Mellomørebetennelse akutt</td>
<td headers="Øre stub_1_37 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_38" scope="row" class="gt_row gt_left gt_stub">h77</th>
<td headers="Øre stub_1_38 icpc2raw_code" class="gt_row gt_center">H77</td>
<td headers="Øre stub_1_38 icpc2group_description_nb" class="gt_row gt_left">Perforert trommehinne IKA</td>
<td headers="Øre stub_1_38 component_nb" class="gt_row gt_left">Skader</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Luftveier">Luftveier</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_39" scope="row" class="gt_row gt_left gt_stub">r01</th>
<td headers="Luftveier stub_1_39 icpc2raw_code" class="gt_row gt_center">R01</td>
<td headers="Luftveier stub_1_39 icpc2group_description_nb" class="gt_row gt_left">Smerte luftveier</td>
<td headers="Luftveier stub_1_39 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_40" scope="row" class="gt_row gt_left gt_stub">r02</th>
<td headers="Luftveier stub_1_40 icpc2raw_code" class="gt_row gt_center">R02</td>
<td headers="Luftveier stub_1_40 icpc2group_description_nb" class="gt_row gt_left">Kortpustethet/dyspné</td>
<td headers="Luftveier stub_1_40 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_41" scope="row" class="gt_row gt_left gt_stub">r03</th>
<td headers="Luftveier stub_1_41 icpc2raw_code" class="gt_row gt_center">R03</td>
<td headers="Luftveier stub_1_41 icpc2group_description_nb" class="gt_row gt_left">Piping i brystet</td>
<td headers="Luftveier stub_1_41 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_42" scope="row" class="gt_row gt_left gt_stub">r04</th>
<td headers="Luftveier stub_1_42 icpc2raw_code" class="gt_row gt_center">R04</td>
<td headers="Luftveier stub_1_42 icpc2group_description_nb" class="gt_row gt_left">Pusteproblem IKA</td>
<td headers="Luftveier stub_1_42 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_43" scope="row" class="gt_row gt_left gt_stub">r05</th>
<td headers="Luftveier stub_1_43 icpc2raw_code" class="gt_row gt_center">R05</td>
<td headers="Luftveier stub_1_43 icpc2group_description_nb" class="gt_row gt_left">Hoste</td>
<td headers="Luftveier stub_1_43 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_44" scope="row" class="gt_row gt_left gt_stub">r06</th>
<td headers="Luftveier stub_1_44 icpc2raw_code" class="gt_row gt_center">R06</td>
<td headers="Luftveier stub_1_44 icpc2group_description_nb" class="gt_row gt_left">Neseblødning</td>
<td headers="Luftveier stub_1_44 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_45" scope="row" class="gt_row gt_left gt_stub">r07</th>
<td headers="Luftveier stub_1_45 icpc2raw_code" class="gt_row gt_center">R07</td>
<td headers="Luftveier stub_1_45 icpc2group_description_nb" class="gt_row gt_left">Nysing/tetthet i nese</td>
<td headers="Luftveier stub_1_45 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_46" scope="row" class="gt_row gt_left gt_stub">r08</th>
<td headers="Luftveier stub_1_46 icpc2raw_code" class="gt_row gt_center">R08</td>
<td headers="Luftveier stub_1_46 icpc2group_description_nb" class="gt_row gt_left">Nese symptomer/plager IKA</td>
<td headers="Luftveier stub_1_46 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_47" scope="row" class="gt_row gt_left gt_stub">r09</th>
<td headers="Luftveier stub_1_47 icpc2raw_code" class="gt_row gt_center">R09</td>
<td headers="Luftveier stub_1_47 icpc2group_description_nb" class="gt_row gt_left">Bihule symptomer/plager IKA</td>
<td headers="Luftveier stub_1_47 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_48" scope="row" class="gt_row gt_left gt_stub">r21</th>
<td headers="Luftveier stub_1_48 icpc2raw_code" class="gt_row gt_center">R21</td>
<td headers="Luftveier stub_1_48 icpc2group_description_nb" class="gt_row gt_left">Hals symptomer/plager</td>
<td headers="Luftveier stub_1_48 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_49" scope="row" class="gt_row gt_left gt_stub">r24</th>
<td headers="Luftveier stub_1_49 icpc2raw_code" class="gt_row gt_center">R24</td>
<td headers="Luftveier stub_1_49 icpc2group_description_nb" class="gt_row gt_left">Blodig oppspytt/hemoptyse</td>
<td headers="Luftveier stub_1_49 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_50" scope="row" class="gt_row gt_left gt_stub">r25</th>
<td headers="Luftveier stub_1_50 icpc2raw_code" class="gt_row gt_center">R25</td>
<td headers="Luftveier stub_1_50 icpc2group_description_nb" class="gt_row gt_left">Unormalt oppspytt/ekspektorat</td>
<td headers="Luftveier stub_1_50 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_51" scope="row" class="gt_row gt_left gt_stub">r27</th>
<td headers="Luftveier stub_1_51 icpc2raw_code" class="gt_row gt_center">R27, R270000</td>
<td headers="Luftveier stub_1_51 icpc2group_description_nb" class="gt_row gt_left">Engstelig for sykdom luftveier IKA</td>
<td headers="Luftveier stub_1_51 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_52" scope="row" class="gt_row gt_left gt_stub">r29</th>
<td headers="Luftveier stub_1_52 icpc2raw_code" class="gt_row gt_center">R29</td>
<td headers="Luftveier stub_1_52 icpc2group_description_nb" class="gt_row gt_left">Luftveier symptomer/plager IKA</td>
<td headers="Luftveier stub_1_52 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_53" scope="row" class="gt_row gt_left gt_stub">r33</th>
<td headers="Luftveier stub_1_53 icpc2raw_code" class="gt_row gt_center">R33</td>
<td headers="Luftveier stub_1_53 icpc2group_description_nb" class="gt_row gt_left">Luftveier mikrobiologisk/immunologisk prøve</td>
<td headers="Luftveier stub_1_53 component_nb" class="gt_row gt_left">Prosesskoder</td></tr>
    <tr><th id="stub_1_54" scope="row" class="gt_row gt_left gt_stub">r71</th>
<td headers="Luftveier stub_1_54 icpc2raw_code" class="gt_row gt_center">R71</td>
<td headers="Luftveier stub_1_54 icpc2group_description_nb" class="gt_row gt_left">Kikhoste</td>
<td headers="Luftveier stub_1_54 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_55" scope="row" class="gt_row gt_left gt_stub">r72</th>
<td headers="Luftveier stub_1_55 icpc2raw_code" class="gt_row gt_center">R72</td>
<td headers="Luftveier stub_1_55 icpc2group_description_nb" class="gt_row gt_left">Streptokokkhals</td>
<td headers="Luftveier stub_1_55 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_56" scope="row" class="gt_row gt_left gt_stub">r74</th>
<td headers="Luftveier stub_1_56 icpc2raw_code" class="gt_row gt_center">R74</td>
<td headers="Luftveier stub_1_56 icpc2group_description_nb" class="gt_row gt_left">Akutt øvre luftveisinfeksjon</td>
<td headers="Luftveier stub_1_56 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_57" scope="row" class="gt_row gt_left gt_stub">r75</th>
<td headers="Luftveier stub_1_57 icpc2raw_code" class="gt_row gt_center">R75</td>
<td headers="Luftveier stub_1_57 icpc2group_description_nb" class="gt_row gt_left">Bihulebetennelse</td>
<td headers="Luftveier stub_1_57 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_58" scope="row" class="gt_row gt_left gt_stub">r76</th>
<td headers="Luftveier stub_1_58 icpc2raw_code" class="gt_row gt_center">R76</td>
<td headers="Luftveier stub_1_58 icpc2group_description_nb" class="gt_row gt_left">Akutt tonsillitt</td>
<td headers="Luftveier stub_1_58 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_59" scope="row" class="gt_row gt_left gt_stub">r77</th>
<td headers="Luftveier stub_1_59 icpc2raw_code" class="gt_row gt_center">R77</td>
<td headers="Luftveier stub_1_59 icpc2group_description_nb" class="gt_row gt_left">Akutt laryngitt/trakeitt</td>
<td headers="Luftveier stub_1_59 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_60" scope="row" class="gt_row gt_left gt_stub">r78</th>
<td headers="Luftveier stub_1_60 icpc2raw_code" class="gt_row gt_center">R78</td>
<td headers="Luftveier stub_1_60 icpc2group_description_nb" class="gt_row gt_left">Akutt bronkitt/bronkiolitt</td>
<td headers="Luftveier stub_1_60 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_61" scope="row" class="gt_row gt_left gt_stub">r79</th>
<td headers="Luftveier stub_1_61 icpc2raw_code" class="gt_row gt_center">R79</td>
<td headers="Luftveier stub_1_61 icpc2group_description_nb" class="gt_row gt_left">Kronisk bronkitt</td>
<td headers="Luftveier stub_1_61 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_62" scope="row" class="gt_row gt_left gt_stub">r80</th>
<td headers="Luftveier stub_1_62 icpc2raw_code" class="gt_row gt_center">R80</td>
<td headers="Luftveier stub_1_62 icpc2group_description_nb" class="gt_row gt_left">Influensa</td>
<td headers="Luftveier stub_1_62 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_63" scope="row" class="gt_row gt_left gt_stub">r81</th>
<td headers="Luftveier stub_1_63 icpc2raw_code" class="gt_row gt_center">R81</td>
<td headers="Luftveier stub_1_63 icpc2group_description_nb" class="gt_row gt_left">Lungebetennelse</td>
<td headers="Luftveier stub_1_63 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_64" scope="row" class="gt_row gt_left gt_stub">r82</th>
<td headers="Luftveier stub_1_64 icpc2raw_code" class="gt_row gt_center">R82</td>
<td headers="Luftveier stub_1_64 icpc2group_description_nb" class="gt_row gt_left">Pleuritt IKA</td>
<td headers="Luftveier stub_1_64 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_65" scope="row" class="gt_row gt_left gt_stub">r83</th>
<td headers="Luftveier stub_1_65 icpc2raw_code" class="gt_row gt_center">R83</td>
<td headers="Luftveier stub_1_65 icpc2group_description_nb" class="gt_row gt_left">Luftveisinfeksjon IKA</td>
<td headers="Luftveier stub_1_65 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_66" scope="row" class="gt_row gt_left gt_stub">r95</th>
<td headers="Luftveier stub_1_66 icpc2raw_code" class="gt_row gt_center">R95</td>
<td headers="Luftveier stub_1_66 icpc2group_description_nb" class="gt_row gt_left">Kronisk obstruktiv lungesykdom</td>
<td headers="Luftveier stub_1_66 component_nb" class="gt_row gt_left">Annet</td></tr>
    <tr><th id="stub_1_67" scope="row" class="gt_row gt_left gt_stub">r96</th>
<td headers="Luftveier stub_1_67 icpc2raw_code" class="gt_row gt_center">R96</td>
<td headers="Luftveier stub_1_67 icpc2group_description_nb" class="gt_row gt_left">Astma</td>
<td headers="Luftveier stub_1_67 component_nb" class="gt_row gt_left">Annet</td></tr>
    <tr><th id="stub_1_68" scope="row" class="gt_row gt_left gt_stub">r99</th>
<td headers="Luftveier stub_1_68 icpc2raw_code" class="gt_row gt_center">R99</td>
<td headers="Luftveier stub_1_68 icpc2group_description_nb" class="gt_row gt_left">Luftveissykdom IKA</td>
<td headers="Luftveier stub_1_68 component_nb" class="gt_row gt_left">Annet</td></tr>
    <tr><th id="stub_1_69" scope="row" class="gt_row gt_left gt_stub">r991</th>
<td headers="Luftveier stub_1_69 icpc2raw_code" class="gt_row gt_center">R991, R9910000</td>
<td headers="Luftveier stub_1_69 icpc2group_description_nb" class="gt_row gt_left">Covid-19 (sannsynlig/mistenkt)</td>
<td headers="Luftveier stub_1_69 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_70" scope="row" class="gt_row gt_left gt_stub">r992</th>
<td headers="Luftveier stub_1_70 icpc2raw_code" class="gt_row gt_center">R992, R9920000</td>
<td headers="Luftveier stub_1_70 icpc2group_description_nb" class="gt_row gt_left">Covid-19 (bekreftet)</td>
<td headers="Luftveier stub_1_70 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_71" scope="row" class="gt_row gt_left gt_stub">respiratory</th>
<td headers="Luftveier stub_1_71 icpc2raw_code" class="gt_row gt_center">R01, R02, R03, R04, R05, R07, R08, R09, R21, R24, R25, R27, R270000, R29, R33, R71, R72, R74, R75, R76, R77, R78, R79, R80, R81, R82, R83, R99, R991, R9910000, R992, R9920000</td>
<td headers="Luftveier stub_1_71 icpc2group_description_nb" class="gt_row gt_left">Luftveisinfeksjoner</td>
<td headers="Luftveier stub_1_71 component_nb" class="gt_row gt_left">Kombinasjon</td></tr>
    <tr><th id="stub_1_72" scope="row" class="gt_row gt_left gt_stub">covid19</th>
<td headers="Luftveier stub_1_72 icpc2raw_code" class="gt_row gt_center">R991, R9910000, R992, R9920000, R33</td>
<td headers="Luftveier stub_1_72 icpc2group_description_nb" class="gt_row gt_left">Covid-19</td>
<td headers="Luftveier stub_1_72 component_nb" class="gt_row gt_left">Kombinasjon</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Hud">Hud</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_73" scope="row" class="gt_row gt_left gt_stub">s06</th>
<td headers="Hud stub_1_73 icpc2raw_code" class="gt_row gt_center">S06</td>
<td headers="Hud stub_1_73 icpc2group_description_nb" class="gt_row gt_left">Lokalisert utslett hud</td>
<td headers="Hud stub_1_73 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_74" scope="row" class="gt_row gt_left gt_stub">s07</th>
<td headers="Hud stub_1_74 icpc2raw_code" class="gt_row gt_center">S07</td>
<td headers="Hud stub_1_74 icpc2group_description_nb" class="gt_row gt_left">Utbredte utslett hud</td>
<td headers="Hud stub_1_74 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_75" scope="row" class="gt_row gt_left gt_stub">s10</th>
<td headers="Hud stub_1_75 icpc2raw_code" class="gt_row gt_center">S10</td>
<td headers="Hud stub_1_75 icpc2group_description_nb" class="gt_row gt_left">Abscess/furunkel</td>
<td headers="Hud stub_1_75 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_76" scope="row" class="gt_row gt_left gt_stub">s12</th>
<td headers="Hud stub_1_76 icpc2raw_code" class="gt_row gt_center">S12</td>
<td headers="Hud stub_1_76 icpc2group_description_nb" class="gt_row gt_left">Insektstikk/bitt</td>
<td headers="Hud stub_1_76 component_nb" class="gt_row gt_left">Skader</td></tr>
    <tr><th id="stub_1_77" scope="row" class="gt_row gt_left gt_stub">s17</th>
<td headers="Hud stub_1_77 icpc2raw_code" class="gt_row gt_center">S17</td>
<td headers="Hud stub_1_77 icpc2group_description_nb" class="gt_row gt_left">Skrubbsår/blemmer</td>
<td headers="Hud stub_1_77 component_nb" class="gt_row gt_left">Skader</td></tr>
    <tr><th id="stub_1_78" scope="row" class="gt_row gt_left gt_stub">s29</th>
<td headers="Hud stub_1_78 icpc2raw_code" class="gt_row gt_center">S29</td>
<td headers="Hud stub_1_78 icpc2group_description_nb" class="gt_row gt_left">Hud symptomer/plager IKA</td>
<td headers="Hud stub_1_78 component_nb" class="gt_row gt_left">Symptomer</td></tr>
    <tr><th id="stub_1_79" scope="row" class="gt_row gt_left gt_stub">s70</th>
<td headers="Hud stub_1_79 icpc2raw_code" class="gt_row gt_center">S70</td>
<td headers="Hud stub_1_79 icpc2group_description_nb" class="gt_row gt_left">Herpes zoster</td>
<td headers="Hud stub_1_79 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_80" scope="row" class="gt_row gt_left gt_stub">s71</th>
<td headers="Hud stub_1_80 icpc2raw_code" class="gt_row gt_center">S71</td>
<td headers="Hud stub_1_80 icpc2group_description_nb" class="gt_row gt_left">Herpes simplex IKA</td>
<td headers="Hud stub_1_80 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_81" scope="row" class="gt_row gt_left gt_stub">s72</th>
<td headers="Hud stub_1_81 icpc2raw_code" class="gt_row gt_center">S72</td>
<td headers="Hud stub_1_81 icpc2group_description_nb" class="gt_row gt_left">Skabb/infestasjon midd</td>
<td headers="Hud stub_1_81 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_82" scope="row" class="gt_row gt_left gt_stub">s73</th>
<td headers="Hud stub_1_82 icpc2raw_code" class="gt_row gt_center">S73</td>
<td headers="Hud stub_1_82 icpc2group_description_nb" class="gt_row gt_left">Infestasjon parasitt IKA</td>
<td headers="Hud stub_1_82 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_83" scope="row" class="gt_row gt_left gt_stub">s76</th>
<td headers="Hud stub_1_83 icpc2raw_code" class="gt_row gt_center">S76</td>
<td headers="Hud stub_1_83 icpc2group_description_nb" class="gt_row gt_left">Hudinfeksjon IKA</td>
<td headers="Hud stub_1_83 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_84" scope="row" class="gt_row gt_left gt_stub">s84</th>
<td headers="Hud stub_1_84 icpc2raw_code" class="gt_row gt_center">S84</td>
<td headers="Hud stub_1_84 icpc2group_description_nb" class="gt_row gt_left">Brennkopper</td>
<td headers="Hud stub_1_84 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_85" scope="row" class="gt_row gt_left gt_stub">s95</th>
<td headers="Hud stub_1_85 icpc2raw_code" class="gt_row gt_center">S95</td>
<td headers="Hud stub_1_85 icpc2group_description_nb" class="gt_row gt_left">Molluscum contagiosum</td>
<td headers="Hud stub_1_85 component_nb" class="gt_row gt_left">Infeksjoner</td></tr>
    <tr><th id="stub_1_86" scope="row" class="gt_row gt_left gt_stub">s99</th>
<td headers="Hud stub_1_86 icpc2raw_code" class="gt_row gt_center">S99</td>
<td headers="Hud stub_1_86 icpc2group_description_nb" class="gt_row gt_left">Hud/underhud sykdom IKA</td>
<td headers="Hud stub_1_86 component_nb" class="gt_row gt_left">Annet</td></tr>
  </tbody>
  
  
</table>
</div><!--/html_preserve-->

<!--html_preserve--><div id="cgmpzsraws" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#cgmpzsraws .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cgmpzsraws .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cgmpzsraws .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cgmpzsraws .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cgmpzsraws .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cgmpzsraws .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cgmpzsraws .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cgmpzsraws .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cgmpzsraws .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cgmpzsraws .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cgmpzsraws .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cgmpzsraws .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cgmpzsraws .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cgmpzsraws .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cgmpzsraws .gt_from_md > :first-child {
  margin-top: 0;
}

#cgmpzsraws .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cgmpzsraws .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cgmpzsraws .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cgmpzsraws .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cgmpzsraws .gt_row_group_first td {
  border-top-width: 2px;
}

#cgmpzsraws .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cgmpzsraws .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cgmpzsraws .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cgmpzsraws .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cgmpzsraws .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cgmpzsraws .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cgmpzsraws .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cgmpzsraws .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cgmpzsraws .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cgmpzsraws .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cgmpzsraws .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cgmpzsraws .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cgmpzsraws .gt_left {
  text-align: left;
}

#cgmpzsraws .gt_center {
  text-align: center;
}

#cgmpzsraws .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cgmpzsraws .gt_font_normal {
  font-weight: normal;
}

#cgmpzsraws .gt_font_bold {
  font-weight: bold;
}

#cgmpzsraws .gt_font_italic {
  font-style: italic;
}

#cgmpzsraws .gt_super {
  font-size: 65%;
}

#cgmpzsraws .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#cgmpzsraws .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cgmpzsraws .gt_indent_1 {
  text-indent: 5px;
}

#cgmpzsraws .gt_indent_2 {
  text-indent: 10px;
}

#cgmpzsraws .gt_indent_3 {
  text-indent: 15px;
}

#cgmpzsraws .gt_indent_4 {
  text-indent: 20px;
}

#cgmpzsraws .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="4" class="gt_heading gt_title gt_font_normal" style>ICPC-2 codes in NorSySS</td>
    </tr>
    <tr>
      <td colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>English</td>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="ICPC-2 codes">ICPC-2 codes</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Description">Description</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Component">Component</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="General and unspecified">General and unspecified</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub">a02</th>
<td headers="General and unspecified stub_1_1 icpc2raw_code" class="gt_row gt_center">A02</td>
<td headers="General and unspecified stub_1_1 icpc2group_description_en" class="gt_row gt_left">Chills</td>
<td headers="General and unspecified stub_1_1 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub">a03</th>
<td headers="General and unspecified stub_1_2 icpc2raw_code" class="gt_row gt_center">A03</td>
<td headers="General and unspecified stub_1_2 icpc2group_description_en" class="gt_row gt_left">Fever</td>
<td headers="General and unspecified stub_1_2 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub">a05</th>
<td headers="General and unspecified stub_1_3 icpc2raw_code" class="gt_row gt_center">A05</td>
<td headers="General and unspecified stub_1_3 icpc2group_description_en" class="gt_row gt_left">Feeling ill</td>
<td headers="General and unspecified stub_1_3 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_left gt_stub">a71</th>
<td headers="General and unspecified stub_1_4 icpc2raw_code" class="gt_row gt_center">A71</td>
<td headers="General and unspecified stub_1_4 icpc2group_description_en" class="gt_row gt_left">Measles</td>
<td headers="General and unspecified stub_1_4 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_left gt_stub">a72</th>
<td headers="General and unspecified stub_1_5 icpc2raw_code" class="gt_row gt_center">A72</td>
<td headers="General and unspecified stub_1_5 icpc2group_description_en" class="gt_row gt_left">Chickenpox</td>
<td headers="General and unspecified stub_1_5 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_left gt_stub">a73</th>
<td headers="General and unspecified stub_1_6 icpc2raw_code" class="gt_row gt_center">A73</td>
<td headers="General and unspecified stub_1_6 icpc2group_description_en" class="gt_row gt_left">Malaria</td>
<td headers="General and unspecified stub_1_6 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_left gt_stub">a74</th>
<td headers="General and unspecified stub_1_7 icpc2raw_code" class="gt_row gt_center">A74</td>
<td headers="General and unspecified stub_1_7 icpc2group_description_en" class="gt_row gt_left">Rubella</td>
<td headers="General and unspecified stub_1_7 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Infections">Infections</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_8" scope="row" class="gt_row gt_left gt_stub">a75</th>
<td headers="Infections stub_1_8 icpc2raw_code" class="gt_row gt_center">A75</td>
<td headers="Infections stub_1_8 icpc2group_description_en" class="gt_row gt_left">Infectious mononucleosis</td>
<td headers="Infections stub_1_8 component_en" class="gt_row gt_left">General and unspecified</td></tr>
    <tr><th id="stub_1_9" scope="row" class="gt_row gt_left gt_stub">a76</th>
<td headers="Infections stub_1_9 icpc2raw_code" class="gt_row gt_center">A76</td>
<td headers="Infections stub_1_9 icpc2group_description_en" class="gt_row gt_left">Viral exanthem other</td>
<td headers="Infections stub_1_9 component_en" class="gt_row gt_left">General and unspecified</td></tr>
    <tr><th id="stub_1_10" scope="row" class="gt_row gt_left gt_stub">a77</th>
<td headers="Infections stub_1_10 icpc2raw_code" class="gt_row gt_center">A77</td>
<td headers="Infections stub_1_10 icpc2group_description_en" class="gt_row gt_left">Viral disease other/NOS</td>
<td headers="Infections stub_1_10 component_en" class="gt_row gt_left">General and unspecified</td></tr>
    <tr><th id="stub_1_11" scope="row" class="gt_row gt_left gt_stub">a78</th>
<td headers="Infections stub_1_11 icpc2raw_code" class="gt_row gt_center">A78</td>
<td headers="Infections stub_1_11 icpc2group_description_en" class="gt_row gt_left">Infectious disease other/NOS</td>
<td headers="Infections stub_1_11 component_en" class="gt_row gt_left">General and unspecified</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Blood, blood forming organs, and immune mechanism">Blood, blood forming organs, and immune mechanism</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_12" scope="row" class="gt_row gt_left gt_stub">b02</th>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_12 icpc2raw_code" class="gt_row gt_center">B02</td>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_12 icpc2group_description_en" class="gt_row gt_left">Lymph gland(s) enlarged/painful</td>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_12 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_13" scope="row" class="gt_row gt_left gt_stub">b70</th>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_13 icpc2raw_code" class="gt_row gt_center">B70</td>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_13 icpc2group_description_en" class="gt_row gt_left">Lymphadenitis acute</td>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_13 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_14" scope="row" class="gt_row gt_left gt_stub">b71</th>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_14 icpc2raw_code" class="gt_row gt_center">B71</td>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_14 icpc2group_description_en" class="gt_row gt_left">lymphadenitis non-specific</td>
<td headers="Blood, blood forming organs, and immune mechanism stub_1_14 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Digestive">Digestive</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_15" scope="row" class="gt_row gt_left gt_stub">d01</th>
<td headers="Digestive stub_1_15 icpc2raw_code" class="gt_row gt_center">D01</td>
<td headers="Digestive stub_1_15 icpc2group_description_en" class="gt_row gt_left">Abdominal pain/cramps general</td>
<td headers="Digestive stub_1_15 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_16" scope="row" class="gt_row gt_left gt_stub">d02</th>
<td headers="Digestive stub_1_16 icpc2raw_code" class="gt_row gt_center">D02</td>
<td headers="Digestive stub_1_16 icpc2group_description_en" class="gt_row gt_left">Abdominal pain epigastric</td>
<td headers="Digestive stub_1_16 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_17" scope="row" class="gt_row gt_left gt_stub">d06</th>
<td headers="Digestive stub_1_17 icpc2raw_code" class="gt_row gt_center">D06</td>
<td headers="Digestive stub_1_17 icpc2group_description_en" class="gt_row gt_left">Abdominal pain localized other</td>
<td headers="Digestive stub_1_17 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_18" scope="row" class="gt_row gt_left gt_stub">d08</th>
<td headers="Digestive stub_1_18 icpc2raw_code" class="gt_row gt_center">D08</td>
<td headers="Digestive stub_1_18 icpc2group_description_en" class="gt_row gt_left">Flatulence/gas/belching</td>
<td headers="Digestive stub_1_18 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_19" scope="row" class="gt_row gt_left gt_stub">d09</th>
<td headers="Digestive stub_1_19 icpc2raw_code" class="gt_row gt_center">D09</td>
<td headers="Digestive stub_1_19 icpc2group_description_en" class="gt_row gt_left">Nausea</td>
<td headers="Digestive stub_1_19 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_20" scope="row" class="gt_row gt_left gt_stub">d10</th>
<td headers="Digestive stub_1_20 icpc2raw_code" class="gt_row gt_center">D10</td>
<td headers="Digestive stub_1_20 icpc2group_description_en" class="gt_row gt_left">Vomiting</td>
<td headers="Digestive stub_1_20 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_21" scope="row" class="gt_row gt_left gt_stub">d11</th>
<td headers="Digestive stub_1_21 icpc2raw_code" class="gt_row gt_center">D11</td>
<td headers="Digestive stub_1_21 icpc2group_description_en" class="gt_row gt_left">Diarrhea</td>
<td headers="Digestive stub_1_21 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_22" scope="row" class="gt_row gt_left gt_stub">d14</th>
<td headers="Digestive stub_1_22 icpc2raw_code" class="gt_row gt_center">D14</td>
<td headers="Digestive stub_1_22 icpc2group_description_en" class="gt_row gt_left">Hematemesis/vomiting blood</td>
<td headers="Digestive stub_1_22 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_23" scope="row" class="gt_row gt_left gt_stub">d18</th>
<td headers="Digestive stub_1_23 icpc2raw_code" class="gt_row gt_center">D18</td>
<td headers="Digestive stub_1_23 icpc2group_description_en" class="gt_row gt_left">Change feces/bowel movements</td>
<td headers="Digestive stub_1_23 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_24" scope="row" class="gt_row gt_left gt_stub">d25</th>
<td headers="Digestive stub_1_24 icpc2raw_code" class="gt_row gt_center">D25</td>
<td headers="Digestive stub_1_24 icpc2group_description_en" class="gt_row gt_left">Abdominal distension</td>
<td headers="Digestive stub_1_24 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_25" scope="row" class="gt_row gt_left gt_stub">d29</th>
<td headers="Digestive stub_1_25 icpc2raw_code" class="gt_row gt_center">D29</td>
<td headers="Digestive stub_1_25 icpc2group_description_en" class="gt_row gt_left">Digestive symptom/complaint other</td>
<td headers="Digestive stub_1_25 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_26" scope="row" class="gt_row gt_left gt_stub">d70</th>
<td headers="Digestive stub_1_26 icpc2raw_code" class="gt_row gt_center">D70</td>
<td headers="Digestive stub_1_26 icpc2group_description_en" class="gt_row gt_left">Gastrointestinal infection</td>
<td headers="Digestive stub_1_26 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_27" scope="row" class="gt_row gt_left gt_stub">d73</th>
<td headers="Digestive stub_1_27 icpc2raw_code" class="gt_row gt_center">D73</td>
<td headers="Digestive stub_1_27 icpc2group_description_en" class="gt_row gt_left">Gastroenteritis presumed infection</td>
<td headers="Digestive stub_1_27 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_28" scope="row" class="gt_row gt_left gt_stub">d87</th>
<td headers="Digestive stub_1_28 icpc2raw_code" class="gt_row gt_center">D87</td>
<td headers="Digestive stub_1_28 icpc2group_description_en" class="gt_row gt_left">Stomach function disorder</td>
<td headers="Digestive stub_1_28 component_en" class="gt_row gt_left">Other diagnoses</td></tr>
    <tr><th id="stub_1_29" scope="row" class="gt_row gt_left gt_stub">d99</th>
<td headers="Digestive stub_1_29 icpc2raw_code" class="gt_row gt_center">D99</td>
<td headers="Digestive stub_1_29 icpc2group_description_en" class="gt_row gt_left">Disease digestive system, other</td>
<td headers="Digestive stub_1_29 component_en" class="gt_row gt_left">Other diagnoses</td></tr>
    <tr><th id="stub_1_30" scope="row" class="gt_row gt_left gt_stub">gastroenteritis</th>
<td headers="Digestive stub_1_30 icpc2raw_code" class="gt_row gt_center">D11, D70, D73</td>
<td headers="Digestive stub_1_30 icpc2group_description_en" class="gt_row gt_left">Gastroenteritis</td>
<td headers="Digestive stub_1_30 component_en" class="gt_row gt_left">Combination</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Eye">Eye</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_31" scope="row" class="gt_row gt_left gt_stub">f70</th>
<td headers="Eye stub_1_31 icpc2raw_code" class="gt_row gt_center">F70</td>
<td headers="Eye stub_1_31 icpc2group_description_en" class="gt_row gt_left">Conjunctivitis infectious</td>
<td headers="Eye stub_1_31 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_32" scope="row" class="gt_row gt_left gt_stub">f73</th>
<td headers="Eye stub_1_32 icpc2raw_code" class="gt_row gt_center">F73</td>
<td headers="Eye stub_1_32 icpc2group_description_en" class="gt_row gt_left">Eye infection/inflammation other</td>
<td headers="Eye stub_1_32 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Ear">Ear</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_33" scope="row" class="gt_row gt_left gt_stub">h01</th>
<td headers="Ear stub_1_33 icpc2raw_code" class="gt_row gt_center">H01</td>
<td headers="Ear stub_1_33 icpc2group_description_en" class="gt_row gt_left">Ear pain/earache</td>
<td headers="Ear stub_1_33 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_34" scope="row" class="gt_row gt_left gt_stub">h04</th>
<td headers="Ear stub_1_34 icpc2raw_code" class="gt_row gt_center">H04</td>
<td headers="Ear stub_1_34 icpc2group_description_en" class="gt_row gt_left">Ear discharge</td>
<td headers="Ear stub_1_34 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_35" scope="row" class="gt_row gt_left gt_stub">h13</th>
<td headers="Ear stub_1_35 icpc2raw_code" class="gt_row gt_center">H13</td>
<td headers="Ear stub_1_35 icpc2group_description_en" class="gt_row gt_left">Plugged feeling ear</td>
<td headers="Ear stub_1_35 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_36" scope="row" class="gt_row gt_left gt_stub">h29</th>
<td headers="Ear stub_1_36 icpc2raw_code" class="gt_row gt_center">H29</td>
<td headers="Ear stub_1_36 icpc2group_description_en" class="gt_row gt_left">Ear symptom/complaint other</td>
<td headers="Ear stub_1_36 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_37" scope="row" class="gt_row gt_left gt_stub">h71</th>
<td headers="Ear stub_1_37 icpc2raw_code" class="gt_row gt_center">H71</td>
<td headers="Ear stub_1_37 icpc2group_description_en" class="gt_row gt_left">Acute otitis media/myringitis</td>
<td headers="Ear stub_1_37 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_38" scope="row" class="gt_row gt_left gt_stub">h77</th>
<td headers="Ear stub_1_38 icpc2raw_code" class="gt_row gt_center">H77</td>
<td headers="Ear stub_1_38 icpc2group_description_en" class="gt_row gt_left">Perforation ear drum</td>
<td headers="Ear stub_1_38 component_en" class="gt_row gt_left">Injuries</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Respiratory">Respiratory</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_39" scope="row" class="gt_row gt_left gt_stub">r01</th>
<td headers="Respiratory stub_1_39 icpc2raw_code" class="gt_row gt_center">R01</td>
<td headers="Respiratory stub_1_39 icpc2group_description_en" class="gt_row gt_left">Pain respiratory system</td>
<td headers="Respiratory stub_1_39 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_40" scope="row" class="gt_row gt_left gt_stub">r02</th>
<td headers="Respiratory stub_1_40 icpc2raw_code" class="gt_row gt_center">R02</td>
<td headers="Respiratory stub_1_40 icpc2group_description_en" class="gt_row gt_left">Shortness of breat/dyspnea</td>
<td headers="Respiratory stub_1_40 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_41" scope="row" class="gt_row gt_left gt_stub">r03</th>
<td headers="Respiratory stub_1_41 icpc2raw_code" class="gt_row gt_center">R03</td>
<td headers="Respiratory stub_1_41 icpc2group_description_en" class="gt_row gt_left">Wheezing</td>
<td headers="Respiratory stub_1_41 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_42" scope="row" class="gt_row gt_left gt_stub">r04</th>
<td headers="Respiratory stub_1_42 icpc2raw_code" class="gt_row gt_center">R04</td>
<td headers="Respiratory stub_1_42 icpc2group_description_en" class="gt_row gt_left">Breathing problem, other</td>
<td headers="Respiratory stub_1_42 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_43" scope="row" class="gt_row gt_left gt_stub">r05</th>
<td headers="Respiratory stub_1_43 icpc2raw_code" class="gt_row gt_center">R05</td>
<td headers="Respiratory stub_1_43 icpc2group_description_en" class="gt_row gt_left">Cough</td>
<td headers="Respiratory stub_1_43 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_44" scope="row" class="gt_row gt_left gt_stub">r06</th>
<td headers="Respiratory stub_1_44 icpc2raw_code" class="gt_row gt_center">R06</td>
<td headers="Respiratory stub_1_44 icpc2group_description_en" class="gt_row gt_left">Nose bleed/epistaxis</td>
<td headers="Respiratory stub_1_44 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_45" scope="row" class="gt_row gt_left gt_stub">r07</th>
<td headers="Respiratory stub_1_45 icpc2raw_code" class="gt_row gt_center">R07</td>
<td headers="Respiratory stub_1_45 icpc2group_description_en" class="gt_row gt_left">Sneezing/nasal congestion</td>
<td headers="Respiratory stub_1_45 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_46" scope="row" class="gt_row gt_left gt_stub">r08</th>
<td headers="Respiratory stub_1_46 icpc2raw_code" class="gt_row gt_center">R08</td>
<td headers="Respiratory stub_1_46 icpc2group_description_en" class="gt_row gt_left">Nose symptom/complaint other</td>
<td headers="Respiratory stub_1_46 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_47" scope="row" class="gt_row gt_left gt_stub">r09</th>
<td headers="Respiratory stub_1_47 icpc2raw_code" class="gt_row gt_center">R09</td>
<td headers="Respiratory stub_1_47 icpc2group_description_en" class="gt_row gt_left">Sinus symptom/complaint</td>
<td headers="Respiratory stub_1_47 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_48" scope="row" class="gt_row gt_left gt_stub">r21</th>
<td headers="Respiratory stub_1_48 icpc2raw_code" class="gt_row gt_center">R21</td>
<td headers="Respiratory stub_1_48 icpc2group_description_en" class="gt_row gt_left">Throat symptom/complaint</td>
<td headers="Respiratory stub_1_48 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_49" scope="row" class="gt_row gt_left gt_stub">r24</th>
<td headers="Respiratory stub_1_49 icpc2raw_code" class="gt_row gt_center">R24</td>
<td headers="Respiratory stub_1_49 icpc2group_description_en" class="gt_row gt_left">Hemoptysis</td>
<td headers="Respiratory stub_1_49 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_50" scope="row" class="gt_row gt_left gt_stub">r25</th>
<td headers="Respiratory stub_1_50 icpc2raw_code" class="gt_row gt_center">R25</td>
<td headers="Respiratory stub_1_50 icpc2group_description_en" class="gt_row gt_left">Sputum/phlegm abnormal</td>
<td headers="Respiratory stub_1_50 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_51" scope="row" class="gt_row gt_left gt_stub">r27</th>
<td headers="Respiratory stub_1_51 icpc2raw_code" class="gt_row gt_center">R27, R270000</td>
<td headers="Respiratory stub_1_51 icpc2group_description_en" class="gt_row gt_left">Fear of respiratory disease, other</td>
<td headers="Respiratory stub_1_51 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_52" scope="row" class="gt_row gt_left gt_stub">r29</th>
<td headers="Respiratory stub_1_52 icpc2raw_code" class="gt_row gt_center">R29</td>
<td headers="Respiratory stub_1_52 icpc2group_description_en" class="gt_row gt_left">Respiratory symptom/complaint other</td>
<td headers="Respiratory stub_1_52 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_53" scope="row" class="gt_row gt_left gt_stub">r33</th>
<td headers="Respiratory stub_1_53 icpc2raw_code" class="gt_row gt_center">R33</td>
<td headers="Respiratory stub_1_53 icpc2group_description_en" class="gt_row gt_left">Respiratory microbiological/immunological test</td>
<td headers="Respiratory stub_1_53 component_en" class="gt_row gt_left">Process codes</td></tr>
    <tr><th id="stub_1_54" scope="row" class="gt_row gt_left gt_stub">r71</th>
<td headers="Respiratory stub_1_54 icpc2raw_code" class="gt_row gt_center">R71</td>
<td headers="Respiratory stub_1_54 icpc2group_description_en" class="gt_row gt_left">Whooping cough</td>
<td headers="Respiratory stub_1_54 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_55" scope="row" class="gt_row gt_left gt_stub">r72</th>
<td headers="Respiratory stub_1_55 icpc2raw_code" class="gt_row gt_center">R72</td>
<td headers="Respiratory stub_1_55 icpc2group_description_en" class="gt_row gt_left">Strep throat</td>
<td headers="Respiratory stub_1_55 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_56" scope="row" class="gt_row gt_left gt_stub">r74</th>
<td headers="Respiratory stub_1_56 icpc2raw_code" class="gt_row gt_center">R74</td>
<td headers="Respiratory stub_1_56 icpc2group_description_en" class="gt_row gt_left">Upper respiratory infection acute</td>
<td headers="Respiratory stub_1_56 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_57" scope="row" class="gt_row gt_left gt_stub">r75</th>
<td headers="Respiratory stub_1_57 icpc2raw_code" class="gt_row gt_center">R75</td>
<td headers="Respiratory stub_1_57 icpc2group_description_en" class="gt_row gt_left">Sinusitis acute/chronic</td>
<td headers="Respiratory stub_1_57 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_58" scope="row" class="gt_row gt_left gt_stub">r76</th>
<td headers="Respiratory stub_1_58 icpc2raw_code" class="gt_row gt_center">R76</td>
<td headers="Respiratory stub_1_58 icpc2group_description_en" class="gt_row gt_left">Tonsillitis acute</td>
<td headers="Respiratory stub_1_58 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_59" scope="row" class="gt_row gt_left gt_stub">r77</th>
<td headers="Respiratory stub_1_59 icpc2raw_code" class="gt_row gt_center">R77</td>
<td headers="Respiratory stub_1_59 icpc2group_description_en" class="gt_row gt_left">Laryngitis/tracheitis acute</td>
<td headers="Respiratory stub_1_59 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_60" scope="row" class="gt_row gt_left gt_stub">r78</th>
<td headers="Respiratory stub_1_60 icpc2raw_code" class="gt_row gt_center">R78</td>
<td headers="Respiratory stub_1_60 icpc2group_description_en" class="gt_row gt_left">Acute bronchitis/bronchiolitis</td>
<td headers="Respiratory stub_1_60 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_61" scope="row" class="gt_row gt_left gt_stub">r79</th>
<td headers="Respiratory stub_1_61 icpc2raw_code" class="gt_row gt_center">R79</td>
<td headers="Respiratory stub_1_61 icpc2group_description_en" class="gt_row gt_left">Chronic bronchitis</td>
<td headers="Respiratory stub_1_61 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_62" scope="row" class="gt_row gt_left gt_stub">r80</th>
<td headers="Respiratory stub_1_62 icpc2raw_code" class="gt_row gt_center">R80</td>
<td headers="Respiratory stub_1_62 icpc2group_description_en" class="gt_row gt_left">Influenza</td>
<td headers="Respiratory stub_1_62 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_63" scope="row" class="gt_row gt_left gt_stub">r81</th>
<td headers="Respiratory stub_1_63 icpc2raw_code" class="gt_row gt_center">R81</td>
<td headers="Respiratory stub_1_63 icpc2group_description_en" class="gt_row gt_left">Pneumonia</td>
<td headers="Respiratory stub_1_63 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_64" scope="row" class="gt_row gt_left gt_stub">r82</th>
<td headers="Respiratory stub_1_64 icpc2raw_code" class="gt_row gt_center">R82</td>
<td headers="Respiratory stub_1_64 icpc2group_description_en" class="gt_row gt_left">Pleurisy/pleural effusion</td>
<td headers="Respiratory stub_1_64 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_65" scope="row" class="gt_row gt_left gt_stub">r83</th>
<td headers="Respiratory stub_1_65 icpc2raw_code" class="gt_row gt_center">R83</td>
<td headers="Respiratory stub_1_65 icpc2group_description_en" class="gt_row gt_left">Respiratory infection other</td>
<td headers="Respiratory stub_1_65 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_66" scope="row" class="gt_row gt_left gt_stub">r95</th>
<td headers="Respiratory stub_1_66 icpc2raw_code" class="gt_row gt_center">R95</td>
<td headers="Respiratory stub_1_66 icpc2group_description_en" class="gt_row gt_left">Chronic obstructive pulmonary disorder</td>
<td headers="Respiratory stub_1_66 component_en" class="gt_row gt_left">Other diagnoses</td></tr>
    <tr><th id="stub_1_67" scope="row" class="gt_row gt_left gt_stub">r96</th>
<td headers="Respiratory stub_1_67 icpc2raw_code" class="gt_row gt_center">R96</td>
<td headers="Respiratory stub_1_67 icpc2group_description_en" class="gt_row gt_left">Asthma</td>
<td headers="Respiratory stub_1_67 component_en" class="gt_row gt_left">Other diagnoses</td></tr>
    <tr><th id="stub_1_68" scope="row" class="gt_row gt_left gt_stub">r99</th>
<td headers="Respiratory stub_1_68 icpc2raw_code" class="gt_row gt_center">R99</td>
<td headers="Respiratory stub_1_68 icpc2group_description_en" class="gt_row gt_left">Respiratory disease other</td>
<td headers="Respiratory stub_1_68 component_en" class="gt_row gt_left">Other diagnoses</td></tr>
    <tr><th id="stub_1_69" scope="row" class="gt_row gt_left gt_stub">r991</th>
<td headers="Respiratory stub_1_69 icpc2raw_code" class="gt_row gt_center">R991, R9910000</td>
<td headers="Respiratory stub_1_69 icpc2group_description_en" class="gt_row gt_left">COVID-19 (Probable/Suspected)</td>
<td headers="Respiratory stub_1_69 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_70" scope="row" class="gt_row gt_left gt_stub">r992</th>
<td headers="Respiratory stub_1_70 icpc2raw_code" class="gt_row gt_center">R992, R9920000</td>
<td headers="Respiratory stub_1_70 icpc2group_description_en" class="gt_row gt_left">COVID-19 (Confirmed)</td>
<td headers="Respiratory stub_1_70 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_71" scope="row" class="gt_row gt_left gt_stub">respiratory</th>
<td headers="Respiratory stub_1_71 icpc2raw_code" class="gt_row gt_center">R01, R02, R03, R04, R05, R07, R08, R09, R21, R24, R25, R27, R270000, R29, R33, R71, R72, R74, R75, R76, R77, R78, R79, R80, R81, R82, R83, R99, R991, R9910000, R992, R9920000</td>
<td headers="Respiratory stub_1_71 icpc2group_description_en" class="gt_row gt_left">Respiratory infections</td>
<td headers="Respiratory stub_1_71 component_en" class="gt_row gt_left">Combination</td></tr>
    <tr><th id="stub_1_72" scope="row" class="gt_row gt_left gt_stub">covid19</th>
<td headers="Respiratory stub_1_72 icpc2raw_code" class="gt_row gt_center">R991, R9910000, R992, R9920000, R33</td>
<td headers="Respiratory stub_1_72 icpc2group_description_en" class="gt_row gt_left">COVID-19</td>
<td headers="Respiratory stub_1_72 component_en" class="gt_row gt_left">Combination</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="4" class="gt_group_heading" scope="colgroup" id="Skin">Skin</th>
    </tr>
    <tr class="gt_row_group_first"><th id="stub_1_73" scope="row" class="gt_row gt_left gt_stub">s06</th>
<td headers="Skin stub_1_73 icpc2raw_code" class="gt_row gt_center">S06</td>
<td headers="Skin stub_1_73 icpc2group_description_en" class="gt_row gt_left">Rash localized</td>
<td headers="Skin stub_1_73 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_74" scope="row" class="gt_row gt_left gt_stub">s07</th>
<td headers="Skin stub_1_74 icpc2raw_code" class="gt_row gt_center">S07</td>
<td headers="Skin stub_1_74 icpc2group_description_en" class="gt_row gt_left">Rash generalized</td>
<td headers="Skin stub_1_74 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_75" scope="row" class="gt_row gt_left gt_stub">s10</th>
<td headers="Skin stub_1_75 icpc2raw_code" class="gt_row gt_center">S10</td>
<td headers="Skin stub_1_75 icpc2group_description_en" class="gt_row gt_left">Boil/carbuncle</td>
<td headers="Skin stub_1_75 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_76" scope="row" class="gt_row gt_left gt_stub">s12</th>
<td headers="Skin stub_1_76 icpc2raw_code" class="gt_row gt_center">S12</td>
<td headers="Skin stub_1_76 icpc2group_description_en" class="gt_row gt_left">Insect bite/sting</td>
<td headers="Skin stub_1_76 component_en" class="gt_row gt_left">Injuries</td></tr>
    <tr><th id="stub_1_77" scope="row" class="gt_row gt_left gt_stub">s17</th>
<td headers="Skin stub_1_77 icpc2raw_code" class="gt_row gt_center">S17</td>
<td headers="Skin stub_1_77 icpc2group_description_en" class="gt_row gt_left">Abrasion/scratch/blister</td>
<td headers="Skin stub_1_77 component_en" class="gt_row gt_left">Injuries</td></tr>
    <tr><th id="stub_1_78" scope="row" class="gt_row gt_left gt_stub">s29</th>
<td headers="Skin stub_1_78 icpc2raw_code" class="gt_row gt_center">S29</td>
<td headers="Skin stub_1_78 icpc2group_description_en" class="gt_row gt_left">Skin symptom/complaint other</td>
<td headers="Skin stub_1_78 component_en" class="gt_row gt_left">Symptoms/Complaints</td></tr>
    <tr><th id="stub_1_79" scope="row" class="gt_row gt_left gt_stub">s70</th>
<td headers="Skin stub_1_79 icpc2raw_code" class="gt_row gt_center">S70</td>
<td headers="Skin stub_1_79 icpc2group_description_en" class="gt_row gt_left">Herpes zoster</td>
<td headers="Skin stub_1_79 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_80" scope="row" class="gt_row gt_left gt_stub">s71</th>
<td headers="Skin stub_1_80 icpc2raw_code" class="gt_row gt_center">S71</td>
<td headers="Skin stub_1_80 icpc2group_description_en" class="gt_row gt_left">Herpes simplex</td>
<td headers="Skin stub_1_80 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_81" scope="row" class="gt_row gt_left gt_stub">s72</th>
<td headers="Skin stub_1_81 icpc2raw_code" class="gt_row gt_center">S72</td>
<td headers="Skin stub_1_81 icpc2group_description_en" class="gt_row gt_left">Scabies/other acariasis</td>
<td headers="Skin stub_1_81 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_82" scope="row" class="gt_row gt_left gt_stub">s73</th>
<td headers="Skin stub_1_82 icpc2raw_code" class="gt_row gt_center">S73</td>
<td headers="Skin stub_1_82 icpc2group_description_en" class="gt_row gt_left">Pediculosis/skin infestation other</td>
<td headers="Skin stub_1_82 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_83" scope="row" class="gt_row gt_left gt_stub">s76</th>
<td headers="Skin stub_1_83 icpc2raw_code" class="gt_row gt_center">S76</td>
<td headers="Skin stub_1_83 icpc2group_description_en" class="gt_row gt_left">Skin infection other</td>
<td headers="Skin stub_1_83 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_84" scope="row" class="gt_row gt_left gt_stub">s84</th>
<td headers="Skin stub_1_84 icpc2raw_code" class="gt_row gt_center">S84</td>
<td headers="Skin stub_1_84 icpc2group_description_en" class="gt_row gt_left">Impetigo</td>
<td headers="Skin stub_1_84 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_85" scope="row" class="gt_row gt_left gt_stub">s95</th>
<td headers="Skin stub_1_85 icpc2raw_code" class="gt_row gt_center">S95</td>
<td headers="Skin stub_1_85 icpc2group_description_en" class="gt_row gt_left">Molluscum contagiosum</td>
<td headers="Skin stub_1_85 component_en" class="gt_row gt_left">Infections</td></tr>
    <tr><th id="stub_1_86" scope="row" class="gt_row gt_left gt_stub">s99</th>
<td headers="Skin stub_1_86 icpc2raw_code" class="gt_row gt_center">S99</td>
<td headers="Skin stub_1_86 icpc2group_description_en" class="gt_row gt_left">Skin disease, other</td>
<td headers="Skin stub_1_86 component_en" class="gt_row gt_left">Other diagnoses</td></tr>
  </tbody>
  
  
</table>
</div><!--/html_preserve-->
