---
title: "Introduction"
date: "2023-06-15"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---





As of 2023-06-15, NorSySS holds 421 204 173 consultations with general practitioners and out-of-hours primary care facilities between 2006-01-02 and 2023-06-11.

<!--html_preserve--><div id="ipbulqekop" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ipbulqekop table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ipbulqekop thead, #ipbulqekop tbody, #ipbulqekop tfoot, #ipbulqekop tr, #ipbulqekop td, #ipbulqekop th {
  border-style: none;
}

#ipbulqekop p {
  margin: 0;
  padding: 0;
}

#ipbulqekop .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ipbulqekop .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ipbulqekop .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ipbulqekop .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ipbulqekop .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ipbulqekop .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ipbulqekop .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ipbulqekop .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ipbulqekop .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ipbulqekop .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ipbulqekop .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ipbulqekop .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ipbulqekop .gt_spanner_row {
  border-bottom-style: hidden;
}

#ipbulqekop .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ipbulqekop .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ipbulqekop .gt_from_md > :first-child {
  margin-top: 0;
}

#ipbulqekop .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ipbulqekop .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ipbulqekop .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ipbulqekop .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ipbulqekop .gt_row_group_first td {
  border-top-width: 2px;
}

#ipbulqekop .gt_row_group_first th {
  border-top-width: 2px;
}

#ipbulqekop .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ipbulqekop .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ipbulqekop .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ipbulqekop .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ipbulqekop .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ipbulqekop .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ipbulqekop .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ipbulqekop .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ipbulqekop .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ipbulqekop .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ipbulqekop .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ipbulqekop .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ipbulqekop .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ipbulqekop .gt_left {
  text-align: left;
}

#ipbulqekop .gt_center {
  text-align: center;
}

#ipbulqekop .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ipbulqekop .gt_font_normal {
  font-weight: normal;
}

#ipbulqekop .gt_font_bold {
  font-weight: bold;
}

#ipbulqekop .gt_font_italic {
  font-style: italic;
}

#ipbulqekop .gt_super {
  font-size: 65%;
}

#ipbulqekop .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ipbulqekop .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ipbulqekop .gt_indent_1 {
  text-indent: 5px;
}

#ipbulqekop .gt_indent_2 {
  text-indent: 10px;
}

#ipbulqekop .gt_indent_3 {
  text-indent: 15px;
}

#ipbulqekop .gt_indent_4 {
  text-indent: 20px;
}

#ipbulqekop .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_title gt_font_normal" style>Consultations in NorSySS</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>2006-01-20 to 2023-06-11</td>
    </tr>
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="3" scope="colgroup" id="Time">
        <span class="gt_column_spanner">Time</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="1" scope="col" id="Consultations">
        <span class="gt_column_spanner">Consultations</span>
      </th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Isoyear">Isoyear</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Min">Min</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Max">Max</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Number">Number</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="isoyear" class="gt_row gt_center">2006</td>
<td headers="date_min" class="gt_row gt_center">2006-01-02</td>
<td headers="date_max" class="gt_row gt_center">2006-12-31</td>
<td headers="consultations_n" class="gt_row gt_center">19 739 344</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2007</td>
<td headers="date_min" class="gt_row gt_center">2007-01-01</td>
<td headers="date_max" class="gt_row gt_center">2007-12-30</td>
<td headers="consultations_n" class="gt_row gt_center">20 583 980</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2008</td>
<td headers="date_min" class="gt_row gt_center">2007-12-31</td>
<td headers="date_max" class="gt_row gt_center">2008-12-28</td>
<td headers="consultations_n" class="gt_row gt_center">21 798 361</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2009</td>
<td headers="date_min" class="gt_row gt_center">2008-12-29</td>
<td headers="date_max" class="gt_row gt_center">2010-01-03</td>
<td headers="consultations_n" class="gt_row gt_center">23 771 522</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2010</td>
<td headers="date_min" class="gt_row gt_center">2010-01-04</td>
<td headers="date_max" class="gt_row gt_center">2011-01-02</td>
<td headers="consultations_n" class="gt_row gt_center">23 987 847</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2011</td>
<td headers="date_min" class="gt_row gt_center">2011-01-03</td>
<td headers="date_max" class="gt_row gt_center">2012-01-01</td>
<td headers="consultations_n" class="gt_row gt_center">24 960 034</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2012</td>
<td headers="date_min" class="gt_row gt_center">2012-01-02</td>
<td headers="date_max" class="gt_row gt_center">2012-12-30</td>
<td headers="consultations_n" class="gt_row gt_center">24 624 010</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2013</td>
<td headers="date_min" class="gt_row gt_center">2012-12-31</td>
<td headers="date_max" class="gt_row gt_center">2013-12-29</td>
<td headers="consultations_n" class="gt_row gt_center">23 168 876</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2014</td>
<td headers="date_min" class="gt_row gt_center">2013-12-30</td>
<td headers="date_max" class="gt_row gt_center">2014-12-28</td>
<td headers="consultations_n" class="gt_row gt_center">23 492 814</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2015</td>
<td headers="date_min" class="gt_row gt_center">2014-12-29</td>
<td headers="date_max" class="gt_row gt_center">2016-01-03</td>
<td headers="consultations_n" class="gt_row gt_center">24 256 036</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2016</td>
<td headers="date_min" class="gt_row gt_center">2016-01-04</td>
<td headers="date_max" class="gt_row gt_center">2017-01-01</td>
<td headers="consultations_n" class="gt_row gt_center">24 657 816</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2017</td>
<td headers="date_min" class="gt_row gt_center">2017-01-02</td>
<td headers="date_max" class="gt_row gt_center">2017-12-31</td>
<td headers="consultations_n" class="gt_row gt_center">24 385 641</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2018</td>
<td headers="date_min" class="gt_row gt_center">2018-01-01</td>
<td headers="date_max" class="gt_row gt_center">2018-12-30</td>
<td headers="consultations_n" class="gt_row gt_center">23 369 284</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2019</td>
<td headers="date_min" class="gt_row gt_center">2018-12-31</td>
<td headers="date_max" class="gt_row gt_center">2019-12-29</td>
<td headers="consultations_n" class="gt_row gt_center">22 976 121</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2020</td>
<td headers="date_min" class="gt_row gt_center">2019-12-30</td>
<td headers="date_max" class="gt_row gt_center">2021-01-03</td>
<td headers="consultations_n" class="gt_row gt_center">27 066 506</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2021</td>
<td headers="date_min" class="gt_row gt_center">2021-01-04</td>
<td headers="date_max" class="gt_row gt_center">2022-01-02</td>
<td headers="consultations_n" class="gt_row gt_center">28 881 122</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2022</td>
<td headers="date_min" class="gt_row gt_center">2022-01-03</td>
<td headers="date_max" class="gt_row gt_center">2023-01-01</td>
<td headers="consultations_n" class="gt_row gt_center">27 090 965</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_center">2023</td>
<td headers="date_min" class="gt_row gt_center">2023-01-02</td>
<td headers="date_max" class="gt_row gt_center">2023-06-11</td>
<td headers="consultations_n" class="gt_row gt_center">12 393 894</td></tr>
  </tbody>
  
  
</table>
</div><!--/html_preserve-->




