---
title: "Registration delay / Registeringsforsinkelse"
date: "2023-06-15"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Registration delay / Registeringsforsinkelse}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---



<!--html_preserve--><div id="rifassfmcs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#rifassfmcs table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#rifassfmcs thead, #rifassfmcs tbody, #rifassfmcs tfoot, #rifassfmcs tr, #rifassfmcs td, #rifassfmcs th {
  border-style: none;
}

#rifassfmcs p {
  margin: 0;
  padding: 0;
}

#rifassfmcs .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rifassfmcs .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#rifassfmcs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rifassfmcs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rifassfmcs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rifassfmcs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rifassfmcs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rifassfmcs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rifassfmcs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rifassfmcs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rifassfmcs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rifassfmcs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rifassfmcs .gt_spanner_row {
  border-bottom-style: hidden;
}

#rifassfmcs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#rifassfmcs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rifassfmcs .gt_from_md > :first-child {
  margin-top: 0;
}

#rifassfmcs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rifassfmcs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rifassfmcs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#rifassfmcs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#rifassfmcs .gt_row_group_first td {
  border-top-width: 2px;
}

#rifassfmcs .gt_row_group_first th {
  border-top-width: 2px;
}

#rifassfmcs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rifassfmcs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#rifassfmcs .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#rifassfmcs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rifassfmcs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rifassfmcs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rifassfmcs .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#rifassfmcs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rifassfmcs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rifassfmcs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rifassfmcs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rifassfmcs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rifassfmcs .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rifassfmcs .gt_left {
  text-align: left;
}

#rifassfmcs .gt_center {
  text-align: center;
}

#rifassfmcs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rifassfmcs .gt_font_normal {
  font-weight: normal;
}

#rifassfmcs .gt_font_bold {
  font-weight: bold;
}

#rifassfmcs .gt_font_italic {
  font-style: italic;
}

#rifassfmcs .gt_super {
  font-size: 65%;
}

#rifassfmcs .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#rifassfmcs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#rifassfmcs .gt_indent_1 {
  text-indent: 5px;
}

#rifassfmcs .gt_indent_2 {
  text-indent: 10px;
}

#rifassfmcs .gt_indent_3 {
  text-indent: 15px;
}

#rifassfmcs .gt_indent_4 {
  text-indent: 20px;
}

#rifassfmcs .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="7" class="gt_heading gt_title gt_font_normal" style>Registration delay in NorSySS by isoyear</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="7" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Days until x% of the consultations are registered</td>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="25%">25%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="50%">50%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="75%">75%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="90%">90%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="95%">95%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="99%">99%</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_right gt_stub">2006</th>
<td headers="stub_1_1 25%" class="gt_row gt_right">14</td>
<td headers="stub_1_1 50%" class="gt_row gt_right">23</td>
<td headers="stub_1_1 75%" class="gt_row gt_right">33</td>
<td headers="stub_1_1 90%" class="gt_row gt_right">49</td>
<td headers="stub_1_1 95%" class="gt_row gt_right">69</td>
<td headers="stub_1_1 99%" class="gt_row gt_right">144</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_right gt_stub">2007</th>
<td headers="stub_1_2 25%" class="gt_row gt_right">14</td>
<td headers="stub_1_2 50%" class="gt_row gt_right">23</td>
<td headers="stub_1_2 75%" class="gt_row gt_right">33</td>
<td headers="stub_1_2 90%" class="gt_row gt_right">49</td>
<td headers="stub_1_2 95%" class="gt_row gt_right">70</td>
<td headers="stub_1_2 99%" class="gt_row gt_right">145</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_right gt_stub">2008</th>
<td headers="stub_1_3 25%" class="gt_row gt_right">14</td>
<td headers="stub_1_3 50%" class="gt_row gt_right">22</td>
<td headers="stub_1_3 75%" class="gt_row gt_right">32</td>
<td headers="stub_1_3 90%" class="gt_row gt_right">48</td>
<td headers="stub_1_3 95%" class="gt_row gt_right">67</td>
<td headers="stub_1_3 99%" class="gt_row gt_right">142</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_right gt_stub">2009</th>
<td headers="stub_1_4 25%" class="gt_row gt_right">13</td>
<td headers="stub_1_4 50%" class="gt_row gt_right">22</td>
<td headers="stub_1_4 75%" class="gt_row gt_right">31</td>
<td headers="stub_1_4 90%" class="gt_row gt_right">47</td>
<td headers="stub_1_4 95%" class="gt_row gt_right">66</td>
<td headers="stub_1_4 99%" class="gt_row gt_right">133</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_right gt_stub">2010</th>
<td headers="stub_1_5 25%" class="gt_row gt_right">6</td>
<td headers="stub_1_5 50%" class="gt_row gt_right">11</td>
<td headers="stub_1_5 75%" class="gt_row gt_right">18</td>
<td headers="stub_1_5 90%" class="gt_row gt_right">29</td>
<td headers="stub_1_5 95%" class="gt_row gt_right">40</td>
<td headers="stub_1_5 99%" class="gt_row gt_right">83</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_right gt_stub">2011</th>
<td headers="stub_1_6 25%" class="gt_row gt_right">5</td>
<td headers="stub_1_6 50%" class="gt_row gt_right">9</td>
<td headers="stub_1_6 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_6 90%" class="gt_row gt_right">22</td>
<td headers="stub_1_6 95%" class="gt_row gt_right">32</td>
<td headers="stub_1_6 99%" class="gt_row gt_right">68</td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_right gt_stub">2012</th>
<td headers="stub_1_7 25%" class="gt_row gt_right">5</td>
<td headers="stub_1_7 50%" class="gt_row gt_right">9</td>
<td headers="stub_1_7 75%" class="gt_row gt_right">15</td>
<td headers="stub_1_7 90%" class="gt_row gt_right">24</td>
<td headers="stub_1_7 95%" class="gt_row gt_right">35</td>
<td headers="stub_1_7 99%" class="gt_row gt_right">76</td></tr>
    <tr><th id="stub_1_8" scope="row" class="gt_row gt_right gt_stub">2013</th>
<td headers="stub_1_8 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_8 50%" class="gt_row gt_right">9</td>
<td headers="stub_1_8 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_8 90%" class="gt_row gt_right">25</td>
<td headers="stub_1_8 95%" class="gt_row gt_right">36</td>
<td headers="stub_1_8 99%" class="gt_row gt_right">83</td></tr>
    <tr><th id="stub_1_9" scope="row" class="gt_row gt_right gt_stub">2014</th>
<td headers="stub_1_9 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_9 50%" class="gt_row gt_right">9</td>
<td headers="stub_1_9 75%" class="gt_row gt_right">15</td>
<td headers="stub_1_9 90%" class="gt_row gt_right">26</td>
<td headers="stub_1_9 95%" class="gt_row gt_right">37</td>
<td headers="stub_1_9 99%" class="gt_row gt_right">85</td></tr>
    <tr><th id="stub_1_10" scope="row" class="gt_row gt_right gt_stub">2015</th>
<td headers="stub_1_10 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_10 50%" class="gt_row gt_right">9</td>
<td headers="stub_1_10 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_10 90%" class="gt_row gt_right">25</td>
<td headers="stub_1_10 95%" class="gt_row gt_right">37</td>
<td headers="stub_1_10 99%" class="gt_row gt_right">82</td></tr>
    <tr><th id="stub_1_11" scope="row" class="gt_row gt_right gt_stub">2016</th>
<td headers="stub_1_11 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_11 50%" class="gt_row gt_right">9</td>
<td headers="stub_1_11 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_11 90%" class="gt_row gt_right">25</td>
<td headers="stub_1_11 95%" class="gt_row gt_right">36</td>
<td headers="stub_1_11 99%" class="gt_row gt_right">85</td></tr>
    <tr><th id="stub_1_12" scope="row" class="gt_row gt_right gt_stub">2017</th>
<td headers="stub_1_12 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_12 50%" class="gt_row gt_right">8</td>
<td headers="stub_1_12 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_12 90%" class="gt_row gt_right">25</td>
<td headers="stub_1_12 95%" class="gt_row gt_right">35</td>
<td headers="stub_1_12 99%" class="gt_row gt_right">82</td></tr>
    <tr><th id="stub_1_13" scope="row" class="gt_row gt_right gt_stub">2018</th>
<td headers="stub_1_13 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_13 50%" class="gt_row gt_right">8</td>
<td headers="stub_1_13 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_13 90%" class="gt_row gt_right">23</td>
<td headers="stub_1_13 95%" class="gt_row gt_right">34</td>
<td headers="stub_1_13 99%" class="gt_row gt_right">89</td></tr>
    <tr><th id="stub_1_14" scope="row" class="gt_row gt_right gt_stub">2019</th>
<td headers="stub_1_14 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_14 50%" class="gt_row gt_right">8</td>
<td headers="stub_1_14 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_14 90%" class="gt_row gt_right">24</td>
<td headers="stub_1_14 95%" class="gt_row gt_right">35</td>
<td headers="stub_1_14 99%" class="gt_row gt_right">94</td></tr>
    <tr><th id="stub_1_15" scope="row" class="gt_row gt_right gt_stub">2020</th>
<td headers="stub_1_15 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_15 50%" class="gt_row gt_right">8</td>
<td headers="stub_1_15 75%" class="gt_row gt_right">15</td>
<td headers="stub_1_15 90%" class="gt_row gt_right">28</td>
<td headers="stub_1_15 95%" class="gt_row gt_right">43</td>
<td headers="stub_1_15 99%" class="gt_row gt_right">145</td></tr>
    <tr><th id="stub_1_16" scope="row" class="gt_row gt_right gt_stub">2021</th>
<td headers="stub_1_16 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_16 50%" class="gt_row gt_right">8</td>
<td headers="stub_1_16 75%" class="gt_row gt_right">15</td>
<td headers="stub_1_16 90%" class="gt_row gt_right">28</td>
<td headers="stub_1_16 95%" class="gt_row gt_right">42</td>
<td headers="stub_1_16 99%" class="gt_row gt_right">116</td></tr>
    <tr><th id="stub_1_17" scope="row" class="gt_row gt_right gt_stub">2022</th>
<td headers="stub_1_17 25%" class="gt_row gt_right">4</td>
<td headers="stub_1_17 50%" class="gt_row gt_right">8</td>
<td headers="stub_1_17 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_17 90%" class="gt_row gt_right">26</td>
<td headers="stub_1_17 95%" class="gt_row gt_right">38</td>
<td headers="stub_1_17 99%" class="gt_row gt_right">96</td></tr>
    <tr><th id="stub_1_18" scope="row" class="gt_row gt_right gt_stub">2023</th>
<td headers="stub_1_18 25%" class="gt_row gt_right">3</td>
<td headers="stub_1_18 50%" class="gt_row gt_right">8</td>
<td headers="stub_1_18 75%" class="gt_row gt_right">14</td>
<td headers="stub_1_18 90%" class="gt_row gt_right">23</td>
<td headers="stub_1_18 95%" class="gt_row gt_right">31</td>
<td headers="stub_1_18 99%" class="gt_row gt_right">57</td></tr>
  </tbody>
  
  
</table>
</div><!--/html_preserve-->





